=== Amtonja/Artifice-Game/Assets/Resources/Files/ArtificeCombatActions.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://tempuri.org/XMLSchema.xsd"
    elementFormDefault="qualified"
    xmlns="http://tempuri.org/XMLSchema.xsd"
    xmlns:mstns="http://tempuri.org/XMLSchema.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>

  <xs:element name="actions">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="action">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="id" type="xs:int" />
              <xs:element name="name" type="xs:string" />
              <xs:element name="description" type="xs:string" />
              <xs:element name="methodname" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
    <xs:unique name="uniqueID">
      <xs:selector xpath="action" />
      <xs:field xpath="id" />
    </xs:unique>
  </xs:element>
</xs:schema>

=== Amtonja/Artifice-Game/Assets/Resources/Files/ArtificeCombatActions.xml
<?xml version="1.0" encoding="utf-8"?>
<actions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ArtificeCombatActions.xsd">
  <!-- SPELLS -->
  <action>
    <id>1</id>
    <name>Gust</name>
    <description>Deals wind-aspected damage to target enemy.</description>
    <methodname>OnGust</methodname>
  </action>
  <action>
    <id>2</id>
    <name>Bolt</name>
    <description>Deals lightning-aspected damage to target enemy.</description>
    <methodname>OnBolt</methodname>
  </action>
  <action>
    <id>3</id>
    <name>Scorch</name>
    <description>Deals fire-aspected damage to target enemy.</description>
    <methodname>OnScorch</methodname>
  </action>
  <action>
    <id>4</id>
    <name>Frost</name>
    <description>Deals ice-aspected damage to target enemy.</description>
    <methodname>OnFrost</methodname>
  </action>
  <action>
    <id>5</id>
    <name>Gravity</name>
    <description>Deals force damage to target enemy.</description>
    <methodname>OnGravity</methodname>
  </action>
  <action>
    <id>6</id>
    <name>Cure</name>
    <description>Restores health to target ally.</description>
    <methodname>OnCure</methodname>
  </action>
</actions>
