=== Amtonja/Artifice-Game/Assets/Resources/Files/ArtificeCharacterStats.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="characters">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="character">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="id" type="xs:string" />
              <xs:element name="name" type="xs:string" />
              <xs:element name="level" type="xs:unsignedByte" />
              <xs:element name="attack" type="xs:unsignedByte" />
              <xs:element name="defense" type="xs:unsignedByte" />
              <xs:element name="accuracy" type="xs:unsignedByte" />
              <xs:element name="magic" type="xs:unsignedByte" />
              <xs:element name="magic_defense" type="xs:unsignedByte" />
              <xs:element name="evasion" type="xs:unsignedByte" />
              <xs:element name="speed" type="xs:unsignedByte" />
              <xs:element name="max_health" type="xs:unsignedInt"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
    <xs:unique name="uniqueID">
      <xs:selector xpath="character" />
      <xs:field xpath="id" />
    </xs:unique>
  </xs:element>
</xs:schema>

=== Amtonja/Artifice-Game/Assets/Resources/Files/ArtificeCharacterStats.xml
<?xml version="1.0" encoding="utf-8"?>
<characters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ArtificeCharacterStats.xsd">
  <!-- PLAYABLE CHARACTERS -->
  <character>
    <id>_hurley_</id>
    <name>Hurley</name>
    <level>1</level>
    <attack>10</attack>
    <defense>11</defense>
    <magic>9</magic>
    <magic_defense>9</magic_defense>
    <speed>7</speed>
    <max_health>85</max_health>
    <xp_value>0</xp_value>
  </character>
  <character>
    <id>_evans_</id>
    <name>Evans</name>
    <level>1</level>
    <attack>9</attack>
    <defense>10</defense>
    <magic>8</magic>
    <magic_defense>7</magic_defense>
    <speed>10</speed>
    <max_health>70</max_health>
    <xp_value>0</xp_value>
  </character>
  <character>
    <id>_stanz_</id>
    <name>Stanz</name>
    <level>1</level>
    <attack>10</attack>
    <defense>9</defense>
    <magic>20</magic>
    <magic_defense>6</magic_defense>
    <speed>6</speed>
    <max_health>175</max_health>
    <xp_value>0</xp_value>
  </character>
  <character>
    <id>_russo_</id>
    <name>Russo</name>
    <level>1</level>
    <attack>8</attack>
    <defense>9</defense>
    <magic>7</magic>
    <magic_defense>9</magic_defense>
    <speed>8</speed>
    <max_health>75</max_health>
    <xp_value>0</xp_value>
  </character>
  
  <!-- NPCs -->
  <character>
    <id>_republicgunner_</id>
    <name>Republic Gunner</name>
    <level>1</level>
    <attack>8</attack>
    <defense>3</defense>
    <magic>10</magic>
    <magic_defense>2</magic_defense>
    <speed>8</speed>
    <max_health>80</max_health>
    <xp_value>50</xp_value>
  </character>
  
  <!-- CREATURES -->
  <character>
    <id>_republiceye_</id>
    <name>Republic Eye</name>
    <level>1</level>
    <attack>0</attack>
    <defense>7</defense>
    <magic>15</magic>
    <magic_defense>5</magic_defense>
    <speed>5</speed>
    <max_health>60</max_health>
    <xp_value>50</xp_value>
  </character>
  <character>
    <id>_komodo_</id>
    <name>Komodo</name>
    <level>1</level>
    <attack>12</attack>
    <defense>2</defense>
    <magic>12</magic>
    <magic_defense>3</magic_defense>
    <speed>9</speed>
    <max_health>50</max_health>
    <xp_value>50</xp_value>
  </character>
  <character>
    <id>_scorpio_</id>
    <name>Scorpio</name>
    <level>1</level>
    <attack>6</attack>
    <defense>8</defense>
    <magic>0</magic>
    <magic_defense>5</magic_defense>
    <speed>7</speed>
    <max_health>40</max_health>
    <xp_value>50</xp_value>
  </character>
  <character>
    <id>_ancienteye_</id>
    <name>Ancient Eye</name>
    <level>1</level>
    <attack>8</attack>
    <defense>7</defense>
    <magic>0</magic>
    <magic_defense>10</magic_defense>
    <speed>9</speed>
    <max_health>35</max_health>
    <xp_value>50</xp_value>
  </character>
  <character>
    <id>_desertmarauder_</id>
    <name>Desert Marauder</name>
    <level>1</level>
    <attack>7</attack>
    <defense>9</defense>
    <magic>0</magic>
    <magic_defense>8</magic_defense>
    <speed>8</speed>
    <max_health>55</max_health>
    <xp_value>50</xp_value>
  </character>
</characters>
